name: sayings
description: A Flutter library providing categorized quotes/sayings with multilingual support.
version: 0.0.5
homepage: https://github.com/shichen437/sayings
repository: https://github.com/shichen437/sayings.git

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - lib/data/index.json
    - lib/data/en/
    - lib/data/zh/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0